---
title: "Eduvos Graduate Dashboard"
author: "Masindi Managa"
format: html
editor: visual
server: shiny
---

```{r}
#| context: setup
library(shiny)
library(shinydashboard)
library(ggplot2)
library(DT)
library(tidyr)
library(dplyr)
library(readr)
library(stringr)


subset_data <- read_csv("subset_data.csv") 
```
#{.sidebar}

```{r}
sliderInput('sampleSize', 'Sample Size', 
            min=1, max=nrow(subset_data),
            value=min(1000, nrow(subset_data)), 
            step=500, round=0)

br()
checkboxGroupInput("tech_tools","Select Tech Tools:", choices = names(subset_data)[names(subset_data) %in% c("ProgLang", "Databases", "AISearch", "AITool", "WebFramework", "Platform")])
```

#Plot

```{r}
plotOutput("techplot")
DTOutput("techTable")
```

```{r}
#| context: server
filtered_data <- reactive({
  req(input$tech_tools)
  
  subset_data %>%
    select(all_of(input$tech_tools)) %>%
    pivot_longer(cols = everything(), names_to = "Category", values_to = "Tools") %>% 
    mutate(Tools = str_split(Tools, ";")) %>%
    unnest(Tools) %>%
    count(Tools, sort = TRUE)
})

output$techplot <- renderPlot({
  ggplot(filtered_data(), aes(x = reorder(Tools, n), y = n, fill = Tools)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Most Used Tech Tools", x = "Tool", y = "Count") +
    theme_minimal()
})

output$techTable <- renderDT({
  datatable(filtered_data())
})
```


